AP-9380: added build instruction to exclude curvesapi
... otherwise the runtime doc builder chokes with...
org.osgi.framework.BundleException: Could not resolve module:
org.knime.ext.poi2 [941]
  Unresolved requirement: Require-Bundle:
org.apache.servicemix.bundles.poi; bundle-version="[3.17.0,4.0.0)"
    -> Bundle-SymbolicName: org.apache.servicemix.bundles.poi;
bundle-version="3.17.0.1"
       org.apache.servicemix.bundles.poi [239]
         Unresolved requirement: Import-Package: com.graphbuilder.curve

        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634)


AP-9380 (Upgrade Excel processing library (Apache POI) to version 3.17
(fixes issues reported in forum))