added optional dependency to santuario.xmlsec
... without it you'll get messages such as below when starting KNIME
from, at least the SDK:

!ENTRY org.knime.ext.poi2 4 0 2020-06-17 22:54:56.164
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module:
org.knime.ext.poi2 [1432]
  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint
violation. Unable to resolve resource org.knime.ext.poi2 [osgi.identity;
osgi.identity="org.knime.ext.poi2"; type="osgi.bundle";
version:Version="4.2.0.qualifier"; singleton:="true"] because it is
exposed to package 'javax.xml.crypto' from resources org.eclipse.osgi
[osgi.identity; type="osgi.bundle";
version:Version="3.15.200.v20200214-1600";
osgi.identity="org.eclipse.osgi"; singleton:="true"] and
org.apache.santuario.xmlsec [osgi.identity; type="osgi.bundle";
version:Version="1.5.8"; osgi.identity="org.apache.santuario.xmlsec"]
via two dependency chains.

Chain 1:
  org.knime.ext.poi2 [osgi.identity; osgi.identity="org.knime.ext.poi2";
type="osgi.bundle"; version:Version="4.2.0.qualifier";
singleton:="true"]
    require:
(&(osgi.wiring.bundle=org.eclipse.core.runtime)(&(bundle-version>=3.6.0)(!(bundle-version>=4.0.0))))
     |
    provide: osgi.wiring.bundle: org.eclipse.core.runtime
  org.eclipse.osgi [osgi.identity; type="osgi.bundle";
version:Version="3.15.200.v20200214-1600";
osgi.identity="org.eclipse.osgi"; singleton:="true"]

Chain 2:
  org.knime.ext.poi2 [osgi.identity; osgi.identity="org.knime.ext.poi2";
type="osgi.bundle"; version:Version="4.2.0.qualifier";
singleton:="true"]
    require:
(&(osgi.wiring.bundle=org.apache.servicemix.bundles.poi)(&(bundle-version>=3.17.1)(!(bundle-version>=4.0.0))))
     |
    provide: osgi.wiring.bundle;
bundle-version:Version="3.17.1.v20200529-knime";
osgi.wiring.bundle="org.apache.servicemix.bundles.poi"
  org.apache.servicemix.bundles.poi [osgi.identity; type="osgi.bundle";
version:Version="3.17.1.v20200529-knime";
osgi.identity="org.apache.servicemix.bundles.poi"]
    import: (osgi.wiring.package=org.apache.jcp.xml.dsig.internal.dom)
     |
    export: osgi.wiring.package: org.apache.jcp.xml.dsig.internal.dom;
uses:=javax.xml.crypto
    export: osgi.wiring.package=javax.xml.crypto
  org.apache.santuario.xmlsec [osgi.identity; type="osgi.bundle";
version:Version="1.5.8"; osgi.identity="org.apache.santuario.xmlsec"]
	at org.eclipse.osgi.container.Module.start(Module.java:462)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1844)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1837)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1778)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1742)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)